"use strict";
exports.__esModule = true;
var forFirstTask_1 = require("./utils/forFirstTask");
var Flowcharts_1 = require("./utils/Flowcharts");
var piConverter_1 = require("./utils/piConverter");
var splitBill_1 = require("./utils/splitBill");
var selectionProgram_1 = require("./utils/selectionProgram");
var selectionProgram_2 = require("./utils/selectionProgram");
var timesTable_1 = require("./utils/timesTable");
(0, forFirstTask_1.makeSentence)();
(0, Flowcharts_1.flowchart1)();
(0, piConverter_1.workOutPI)();
(0, splitBill_1.printBill)();
(0, selectionProgram_1.animalSelection)();
(0, selectionProgram_2.vegetableSelection)();
(0, timesTable_1.timesTable)();
